# Site settings
title: Materiaterza
email: materiaterza@gmail.com
description: collettivo di processi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://materiaterza.com" # the base hostname & protocol for your site
#twitter_username: materiaterza


# Build settings
markdown: kramdown
excerpt_separator: "\n\n"
