# Site settings
title: Fabrizio Goglia
#email: fabrizio.goglia@gmail.com
description: Process design collective based in Venice
baseurl: "http://materiaterza.com" # the subpath of your site, e.g. /blog/
url: "http://materiaterza.com" # the base hostname & protocol for your site
twitter_username: materiaterza


# Build settings
markdown: kramdown
excerpt_separator: "\n\n"
